In [1]:
print("Hello AI Construction")

Hello AI Construction

In [2]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.5

In [3]:
from pathlib import Path

data_path = Path("../data/raw")

files = list(data_path.glob("*"))

print("Number of files:", len(files))
print("\nFiles:")
for file in files:
    print(file.name)

Number of files: 25

Files:
activities.csv
activity_states.csv
construction_memory.csv
counterfactuals.csv
DATASET_CATALOG.csv
DATA_DICTIONARY.csv
DATA_QUALITY_REPORT.csv
decisions.csv
dependencies.csv
environment.csv
events.csv
friction_canonical.csv
friction_summary_canonical.csv
GENERATION_METHODOLOGY.md
intervention_options.csv
LICENSE.txt
master_projects_canonical.csv
outcomes.csv
procurement.csv
projects.csv
PUBLIC_RELEASE_MANIFEST.json
README.md
resources.csv
resource_allocation.csv
rework.csv

In [4]:
import pandas as pd
from pathlib import Path

data_path = Path("../data/raw")

csv_files = sorted(data_path.glob("*.csv"))

for file in csv_files:
    df = pd.read_csv(file)

    print("=" * 70)
    print("FILE:", file.name)
    print("ROWS:", len(df))
    print("COLUMNS:", len(df.columns))
    print("COLUMN NAMES:")
    print(list(df.columns))

======================================================================
FILE: activities.csv
ROWS: 9279
COLUMNS: 19
COLUMN NAMES:
['project_id', 'activity_id', 'phase', 'phase_order', 'activity_sequence', 'activity_name', 'resource_type', 'planned_duration_days', 'quantity', 'unit_cost', 'planned_cost', 'criticality', 'status', 'critical_path', 'critical_path_position', 'project_network_duration', 'predecessor_count', 'successor_count', 'split']
======================================================================
FILE: activity_states.csv
ROWS: 4060623
COLUMNS: 9
COLUMN NAMES:
['project_id', 'activity_id', 'date', 'day_index', 'productivity_index', 'weather_risk', 'site_access_index', 'event_pressure', 'split']

C:\Users\Asgar\AppData\Local\Temp\ipykernel_33648\900229822.py:9: DtypeWarning: Columns (0: phase, 1: activity_name, 2: decision_type, 3: resource_type) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

======================================================================
FILE: construction_memory.csv
ROWS: 55489
COLUMNS: 24
COLUMN NAMES:
['memory_id', 'project_id', 'activity_id', 'memory_type', 'source', 'phase', 'activity_name', 'event_type', 'decision_type', 'resource_type', 'planned_duration_days', 'planned_cost', 'observed_delay_days', 'observed_rework_days', 'friction_hours', 'criticality', 'severity', 'impact_factor', 'decision_debt_score', 'lesson_score', 'failure_flag', 'reusability_score', 'memory_risk_score', 'split']
======================================================================
FILE: counterfactuals.csv
ROWS: 70513
COLUMNS: 10
COLUMN NAMES:
['intervention_id', 'event_id', 'project_id', 'activity_id', 'baseline_delay_days', 'counterfactual_delay_days', 'avoided_delay_days', 'intervention_cost', 'cost_per_day_avoided', 'split']
======================================================================
FILE: DATA_DICTIONARY.csv
ROWS: 200
COLUMNS: 4
COLUMN NAMES:
['dataset', 'variable', 'datatype', 'description']
======================================================================
FILE: DATA_QUALITY_REPORT.csv
ROWS: 18
COLUMNS: 8
COLUMN NAMES:
['dataset', 'records', 'columns', 'missing_cells', 'missing_percentage', 'duplicate_rows', 'project_id_available', 'status']
======================================================================
FILE: DATASET_CATALOG.csv
ROWS: 18
COLUMNS: 5
COLUMN NAMES:
['dataset', 'records', 'columns', 'missing_cells', 'description']
======================================================================
FILE: decisions.csv
ROWS: 3374
COLUMNS: 15
COLUMN NAMES:
['decision_id', 'project_id', 'activity_id', 'decision_type', 'required_day', 'actual_decision_day', 'decision_delay_days', 'criticality', 'decision_status', 'dependency_exposure', 'time_exposure', 'reversibility_penalty', 'decision_debt_score', 'decision_debt_level', 'split']
======================================================================
FILE: dependencies.csv
ROWS: 18176
COLUMNS: 6
COLUMN NAMES:
['project_id', 'predecessor_id', 'successor_id', 'relationship', 'lag_days', 'split']
======================================================================
FILE: environment.csv
ROWS: 52332
COLUMNS: 10
COLUMN NAMES:
['project_id', 'date', 'day_index', 'rainfall_mm', 'temperature_c', 'humidity_pct', 'site_access_index', 'extreme_weather', 'weather_risk', 'split']
======================================================================
FILE: events.csv
ROWS: 27989
COLUMNS: 10
COLUMN NAMES:
['event_id', 'project_id', 'date', 'activity_id', 'event_type', 'severity', 'duration_days', 'cause_node', 'impact_factor', 'split']
======================================================================
FILE: friction_canonical.csv
ROWS: 12980
COLUMNS: 6
COLUMN NAMES:
['project_id', 'activity_id', 'friction_type', 'friction_duration_hours', 'friction_severity', 'split']
======================================================================
FILE: friction_summary_canonical.csv
ROWS: 100
COLUMNS: 4
COLUMN NAMES:
['project_id', 'total_friction_hours', 'mean_friction_severity', 'friction_events']
======================================================================
FILE: intervention_options.csv
ROWS: 70513
COLUMNS: 11
COLUMN NAMES:
['intervention_id', 'event_id', 'project_id', 'activity_id', 'event_type', 'intervention_type', 'category', 'implementation_days', 'intervention_cost', 'true_effectiveness', 'split']
======================================================================
FILE: master_projects_canonical.csv
ROWS: 100
COLUMNS: 29
COLUMN NAMES:
['project_id', 'project_type', 'floors', 'area_m2', 'complexity', 'contractor_capability', 'resource_availability', 'management_maturity', 'weather_exposure', 'supply_chain_exposure', 'technology_maturity', 'planned_duration_days', 'planned_cost', 'total_activities', 'total_planned_duration', 'total_risk_events', 'high_critical_events', 'total_event_delay', 'total_decisions', 'delayed_decisions', 'total_decision_delay', 'total_decision_debt', 'maximum_decision_debt', 'total_friction_hours', 'friction_event_count', 'mean_friction_severity', 'max_friction_severity', 'construction_friction_index', 'split']
======================================================================
FILE: outcomes.csv
ROWS: 100
COLUMNS: 4
COLUMN NAMES:
['project_id', 'total_activities', 'total_planned_duration', 'split']
======================================================================
FILE: procurement.csv
ROWS: 800
COLUMNS: 8
COLUMN NAMES:
['procurement_id', 'project_id', 'material', 'planned_lead_days', 'actual_lead_days', 'procurement_delay_days', 'supply_chain_risk', 'split']
======================================================================
FILE: projects.csv
ROWS: 100
COLUMNS: 14
COLUMN NAMES:
['project_id', 'project_type', 'floors', 'area_m2', 'complexity', 'contractor_capability', 'resource_availability', 'management_maturity', 'weather_exposure', 'supply_chain_exposure', 'technology_maturity', 'planned_duration_days', 'planned_cost', 'split']
======================================================================
FILE: resource_allocation.csv
ROWS: 9279
COLUMNS: 6
COLUMN NAMES:
['project_id', 'activity_id', 'resource_id', 'resource_category', 'allocation_fraction', 'split']
======================================================================
FILE: resources.csv
ROWS: 2748
COLUMNS: 8
COLUMN NAMES:
['resource_id', 'project_id', 'resource_category', 'resource_type', 'capacity', 'availability', 'daily_cost', 'split']
======================================================================
FILE: rework.csv
ROWS: 1858
COLUMNS: 7
COLUMN NAMES:
['rework_id', 'project_id', 'event_id', 'activity_id', 'rework_days', 'rework_cost', 'split']

In [5]:
import pandas as pd
from pathlib import Path

data_path = Path("../data/raw")

csv_files = sorted(data_path.glob("*.csv"))

summary = []

for file in csv_files:
    df = pd.read_csv(file, low_memory=False)

    summary.append({
        "File": file.name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Missing Cells": int(df.isna().sum().sum()),
        "Duplicate Rows": int(df.duplicated().sum())
    })

summary_df = pd.DataFrame(summary)

summary_df

,File,Rows,Columns,Missing Cells,Duplicate Rows
0,activities.csv,9279,19,0,0
1,activity_states.csv,4060623,9,0,0
2,construction_memory.csv,55489,24,245745,0
3,counterfactuals.csv,70513,10,0,0
4,DATA_DICTIONARY.csv,200,4,0,0
5,DATA_QUALITY_REPORT.csv,18,8,0,0
6,DATASET_CATALOG.csv,18,5,0,0
7,decisions.csv,3374,15,0,0
8,dependencies.csv,18176,6,0,0
9,environment.csv,52332,10,0,0
10,events.csv,27989,10,0,0
11,friction_canonical.csv,12980,6,0,0
12,friction_summary_canonical.csv,100,4,0,0
13,intervention_options.csv,70513,11,0,0
14,master_projects_canonical.csv,100,29,0,0
15,outcomes.csv,100,4,0,0
16,procurement.csv,800,8,0,0
17,projects.csv,100,14,0,0
18,resource_allocation.csv,9279,6,0,0
19,resources.csv,2748,8,0,0
20,rework.csv,1858,7,0,0

In [6]:
import pandas as pd
from pathlib import Path

data_path = Path("../data/raw")

projects = pd.read_csv(
    data_path / "projects.csv",
    low_memory=False
)

print("Shape:", projects.shape)

print("\nColumns:")
print(list(projects.columns))

print("\nData types:")
print(projects.dtypes)

print("\nFirst 5 rows:")
display(projects.head())

Shape: (100, 14)

Columns:
['project_id', 'project_type', 'floors', 'area_m2', 'complexity', 'contractor_capability', 'resource_availability', 'management_maturity', 'weather_exposure', 'supply_chain_exposure', 'technology_maturity', 'planned_duration_days', 'planned_cost', 'split']

Data types:
project_id                   str
project_type                 str
floors                     int64
area_m2                  float64
complexity               float64
contractor_capability    float64
resource_availability    float64
management_maturity      float64
weather_exposure         float64
supply_chain_exposure    float64
technology_maturity      float64
planned_duration_days      int64
planned_cost             float64
split                        str
dtype: object

First 5 rows:

,project_id,project_type,floors,area_m2,complexity,contractor_capability,resource_availability,management_maturity,weather_exposure,supply_chain_exposure,technology_maturity,planned_duration_days,planned_cost,split
0,P00001,Hospital,12,31706.20,0.7112,0.9428,0.8254,0.7383,0.3867,0.4228,0.7584,541,1.128285e+08,validation
1,P00002,Commercial,7,56384.82,0.6882,0.8395,0.8189,0.9593,0.0714,0.3416,0.5060,425,1.946978e+08,train
2,P00003,Hospital,11,61848.91,0.9002,0.6385,0.9800,0.4010,0.4470,0.5078,0.4480,614,2.859703e+08,train
3,P00004,Industrial,5,46523.22,0.8495,0.4374,0.8357,0.7065,0.6243,0.2922,0.6115,422,2.091564e+08,train
4,P00005,Industrial,6,49723.66,0.7282,0.8465,0.7773,0.5635,0.3323,0.5016,0.8031,425,2.478664e+08,train

In [7]:
outcomes = pd.read_csv(
    data_path / "outcomes.csv",
    low_memory=False
)

print("Shape:", outcomes.shape)

print("\nColumns:")
print(list(outcomes.columns))

print("\nData types:")
print(outcomes.dtypes)

print("\nFirst 5 rows:")
display(outcomes.head())

Shape: (100, 4)

Columns:
['project_id', 'total_activities', 'total_planned_duration', 'split']

Data types:
project_id                  str
total_activities          int64
total_planned_duration    int64
split                       str
dtype: object

First 5 rows:

  project_id  total_activities  total_planned_duration       split
0     P00001               107                    1664  validation
1     P00002                81                    1173       train
2     P00003               107                    1671       train
3     P00004                90                    1329       train
4     P00005                83                    1356       train

In [8]:
activities = pd.read_csv(
    data_path / "activities.csv",
    low_memory=False
)

print("Shape:", activities.shape)

print("\nColumns:")
print(list(activities.columns))

print("\nData types:")
print(activities.dtypes)

print("\nFirst 5 rows:")
display(activities.head())

Shape: (9279, 19)

Columns:
['project_id', 'activity_id', 'phase', 'phase_order', 'activity_sequence', 'activity_name', 'resource_type', 'planned_duration_days', 'quantity', 'unit_cost', 'planned_cost', 'criticality', 'status', 'critical_path', 'critical_path_position', 'project_network_duration', 'predecessor_count', 'successor_count', 'split']

Data types:
project_id                      str
activity_id                     str
phase                           str
phase_order                   int64
activity_sequence             int64
activity_name                   str
resource_type                   str
planned_duration_days         int64
quantity                    float64
unit_cost                   float64
planned_cost                float64
criticality                 float64
status                          str
critical_path                 int64
critical_path_position        int64
project_network_duration      int64
predecessor_count             int64
successor_count               int64
split                           str
dtype: object

First 5 rows:

,project_id,activity_id,phase,phase_order,activity_sequence,activity_name,resource_type,planned_duration_days,quantity,unit_cost,planned_cost,criticality,status,critical_path,critical_path_position,project_network_duration,predecessor_count,successor_count,split
0,P00001,P00001_A0001,Preconstruction,1,1,Design Finalisation,information,26,2187.70,2506.01,5482410.95,0.6854,Planned,1,1,386,0,4,validation
1,P00001,P00001_A0002,Preconstruction,1,2,Procurement Planning,management,20,1302.18,2963.97,3859611.57,0.7652,Planned,0,-1,386,1,2,validation
2,P00001,P00001_A0003,Preconstruction,1,3,Design Finalisation,information,29,253.39,4238.86,1074065.75,0.3375,Planned,1,2,386,1,4,validation
3,P00001,P00001_A0004,Preconstruction,1,4,Design Finalisation,information,25,842.14,2417.26,2035675.21,0.5346,Planned,1,3,386,3,1,validation
4,P00001,P00001_A0005,Site Preparation,2,5,Site Clearance,equipment,13,6059.30,1836.91,11130386.93,0.5794,Planned,1,4,386,2,4,validation

In [9]:
dependencies = pd.read_csv(
    data_path / "dependencies.csv",
    low_memory=False
)

print("Shape:", dependencies.shape)

print("\nColumns:")
print(list(dependencies.columns))

print("\nData types:")
print(dependencies.dtypes)

print("\nFirst 10 rows:")
display(dependencies.head(10))

Shape: (18176, 6)

Columns:
['project_id', 'predecessor_id', 'successor_id', 'relationship', 'lag_days', 'split']

Data types:
project_id          str
predecessor_id      str
successor_id        str
relationship        str
lag_days          int64
split               str
dtype: object

First 10 rows:

  project_id predecessor_id  successor_id relationship  lag_days       split
0     P00001   P00001_A0001  P00001_A0002           FS         2  validation
1     P00001   P00001_A0001  P00001_A0003           FS         2  validation
2     P00001   P00001_A0001  P00001_A0004           FF         2  validation
3     P00001   P00001_A0001  P00001_A0009           FS         3  validation
4     P00001   P00001_A0002  P00001_A0004           FS         0  validation
5     P00001   P00001_A0002  P00001_A0006           FS         2  validation
6     P00001   P00001_A0003  P00001_A0004           FS         0  validation
7     P00001   P00001_A0003  P00001_A0005           FS         0  validation
8     P00001   P00001_A0003  P00001_A0007           FS         0  validation
9     P00001   P00001_A0003  P00001_A0008           SS         0  validation

In [10]:
dependencies = pd.read_csv(
    data_path / "dependencies.csv",
    low_memory=False
)

print("Shape:", dependencies.shape)

print("\nColumns:")
print(list(dependencies.columns))

print("\nData types:")
print(dependencies.dtypes)

print("\nFirst 10 rows:")
display(dependencies.head(10))

Shape: (18176, 6)

Columns:
['project_id', 'predecessor_id', 'successor_id', 'relationship', 'lag_days', 'split']

Data types:
project_id          str
predecessor_id      str
successor_id        str
relationship        str
lag_days          int64
split               str
dtype: object

First 10 rows:

  project_id predecessor_id  successor_id relationship  lag_days       split
0     P00001   P00001_A0001  P00001_A0002           FS         2  validation
1     P00001   P00001_A0001  P00001_A0003           FS         2  validation
2     P00001   P00001_A0001  P00001_A0004           FF         2  validation
3     P00001   P00001_A0001  P00001_A0009           FS         3  validation
4     P00001   P00001_A0002  P00001_A0004           FS         0  validation
5     P00001   P00001_A0002  P00001_A0006           FS         2  validation
6     P00001   P00001_A0003  P00001_A0004           FS         0  validation
7     P00001   P00001_A0003  P00001_A0005           FS         0  validation
8     P00001   P00001_A0003  P00001_A0007           FS         0  validation
9     P00001   P00001_A0003  P00001_A0008           SS         0  validation

In [11]:
dependencies = pd.read_csv(
    data_path / "dependencies.csv",
    low_memory=False
)

print("Shape:", dependencies.shape)
print("\nColumns:")
print(list(dependencies.columns))
print("\nData types:")
print(dependencies.dtypes)
print("\nFirst 10 rows:")
display(dependencies.head(10))

Shape: (18176, 6)

Columns:
['project_id', 'predecessor_id', 'successor_id', 'relationship', 'lag_days', 'split']

Data types:
project_id          str
predecessor_id      str
successor_id        str
relationship        str
lag_days          int64
split               str
dtype: object

First 10 rows:

  project_id predecessor_id  successor_id relationship  lag_days       split
0     P00001   P00001_A0001  P00001_A0002           FS         2  validation
1     P00001   P00001_A0001  P00001_A0003           FS         2  validation
2     P00001   P00001_A0001  P00001_A0004           FF         2  validation
3     P00001   P00001_A0001  P00001_A0009           FS         3  validation
4     P00001   P00001_A0002  P00001_A0004           FS         0  validation
5     P00001   P00001_A0002  P00001_A0006           FS         2  validation
6     P00001   P00001_A0003  P00001_A0004           FS         0  validation
7     P00001   P00001_A0003  P00001_A0005           FS         0  validation
8     P00001   P00001_A0003  P00001_A0007           FS         0  validation
9     P00001   P00001_A0003  P00001_A0008           SS         0  validation

In [12]:
events = pd.read_csv(
    data_path / "events.csv",
    low_memory=False
)

print("Shape:", events.shape)
print("\nColumns:")
print(list(events.columns))
print("\nData types:")
print(events.dtypes)
print("\nFirst 10 rows:")
display(events.head(10))

Shape: (27989, 10)

Columns:
['event_id', 'project_id', 'date', 'activity_id', 'event_type', 'severity', 'duration_days', 'cause_node', 'impact_factor', 'split']

Data types:
event_id             str
project_id           str
date                 str
activity_id          str
event_type           str
severity             str
duration_days      int64
cause_node           str
impact_factor    float64
split                str
dtype: object

First 10 rows:

,event_id,project_id,date,activity_id,event_type,severity,duration_days,cause_node,impact_factor,split
0,P00001_E00001,P00001,2024-01-02,P00001_A0026,Rework,Medium,1,Rework,0.50,validation
1,P00001_E00002,P00001,2024-01-13,P00001_A0091,Heavy Rainfall,Low,1,Weather,0.25,validation
2,P00001_E00003,P00001,2024-01-13,P00001_A0092,Subcontractor Delay,Medium,26,Subcontractor Delay,0.50,validation
3,P00001_E00004,P00001,2024-01-16,P00001_A0043,Equipment Breakdown,Low,2,Equipment Breakdown,0.25,validation
4,P00001_E00005,P00001,2024-01-16,P00001_A0019,Material Shortage,Medium,6,Material Shortage,0.50,validation
5,P00001_E00006,P00001,2024-01-18,P00001_A0025,Rework,Medium,6,Rework,0.50,validation
6,P00001_E00007,P00001,2024-01-22,P00001_A0105,Late Design Information,Medium,3,Late Design Information,0.50,validation
7,P00001_E00008,P00001,2024-01-23,P00001_A0049,Quality Failure,High,2,Quality Failure,0.75,validation
8,P00001_E00009,P00001,2024-01-26,P00001_A0087,Late Design Information,High,15,Late Design Information,0.75,validation
9,P00001_E00010,P00001,2024-01-27,P00001_A0002,Subcontractor Delay,Medium,4,Subcontractor Delay,0.50,validation

In [13]:
events = pd.read_csv(
    data_path / "events.csv",
    low_memory=False
)

print("Shape:", events.shape)
print("\nColumns:")
print(list(events.columns))
print("\nData types:")
print(events.dtypes)
print("\nFirst 10 rows:")
display(events.head(10))

Shape: (27989, 10)

Columns:
['event_id', 'project_id', 'date', 'activity_id', 'event_type', 'severity', 'duration_days', 'cause_node', 'impact_factor', 'split']

Data types:
event_id             str
project_id           str
date                 str
activity_id          str
event_type           str
severity             str
duration_days      int64
cause_node           str
impact_factor    float64
split                str
dtype: object

First 10 rows:

,event_id,project_id,date,activity_id,event_type,severity,duration_days,cause_node,impact_factor,split
0,P00001_E00001,P00001,2024-01-02,P00001_A0026,Rework,Medium,1,Rework,0.50,validation
1,P00001_E00002,P00001,2024-01-13,P00001_A0091,Heavy Rainfall,Low,1,Weather,0.25,validation
2,P00001_E00003,P00001,2024-01-13,P00001_A0092,Subcontractor Delay,Medium,26,Subcontractor Delay,0.50,validation
3,P00001_E00004,P00001,2024-01-16,P00001_A0043,Equipment Breakdown,Low,2,Equipment Breakdown,0.25,validation
4,P00001_E00005,P00001,2024-01-16,P00001_A0019,Material Shortage,Medium,6,Material Shortage,0.50,validation
5,P00001_E00006,P00001,2024-01-18,P00001_A0025,Rework,Medium,6,Rework,0.50,validation
6,P00001_E00007,P00001,2024-01-22,P00001_A0105,Late Design Information,Medium,3,Late Design Information,0.50,validation
7,P00001_E00008,P00001,2024-01-23,P00001_A0049,Quality Failure,High,2,Quality Failure,0.75,validation
8,P00001_E00009,P00001,2024-01-26,P00001_A0087,Late Design Information,High,15,Late Design Information,0.75,validation
9,P00001_E00010,P00001,2024-01-27,P00001_A0002,Subcontractor Delay,Medium,4,Subcontractor Delay,0.50,validation

In [14]:
rework = pd.read_csv(
    data_path / "rework.csv",
    low_memory=False
)

print("Shape:", rework.shape)
print("\nColumns:")
print(list(rework.columns))
print("\nData types:")
print(rework.dtypes)
print("\nFirst 10 rows:")
display(rework.head(10))

Shape: (1858, 7)

Columns:
['rework_id', 'project_id', 'event_id', 'activity_id', 'rework_days', 'rework_cost', 'split']

Data types:
rework_id          str
project_id         str
event_id           str
activity_id        str
rework_days      int64
rework_cost    float64
split              str
dtype: object

First 10 rows:

,rework_id,project_id,event_id,activity_id,rework_days,rework_cost,split
0,RW0000001,P00001,P00001_E00006,P00001_A0025,1,9578.96,validation
1,RW0000002,P00001,P00001_E00014,P00001_A0033,6,55095.02,validation
2,RW0000003,P00001,P00001_E00028,P00001_A0089,1,10498.68,validation
3,RW0000004,P00001,P00001_E00034,P00001_A0014,4,12702.75,validation
4,RW0000005,P00001,P00001_E00035,P00001_A0071,6,50161.97,validation
5,RW0000006,P00001,P00001_E00064,P00001_A0021,4,35421.54,validation
6,RW0000007,P00001,P00001_E00144,P00001_A0077,1,11481.37,validation
7,RW0000008,P00001,P00001_E00147,P00001_A0055,3,21722.82,validation
8,RW0000009,P00001,P00001_E00162,P00001_A0084,5,38479.21,validation
9,RW0000010,P00001,P00001_E00168,P00001_A0056,1,5307.57,validation

In [15]:
resources = pd.read_csv(
    data_path / "resources.csv",
    low_memory=False
)

print("Shape:", resources.shape)
print("\nColumns:")
print(list(resources.columns))
print("\nData types:")
print(resources.dtypes)
print("\nFirst 10 rows:")
display(resources.head(10))

Shape: (2748, 8)

Columns:
['resource_id', 'project_id', 'resource_category', 'resource_type', 'capacity', 'availability', 'daily_cost', 'split']

Data types:
resource_id              str
project_id               str
resource_category        str
resource_type            str
capacity             float64
availability         float64
daily_cost           float64
split                    str
dtype: object

First 10 rows:

,resource_id,project_id,resource_category,resource_type,capacity,availability,daily_cost,split
0,P00001_L001,P00001,Labour,Plumber,0.735,0.996,1375.29,validation
1,P00001_L002,P00001,Labour,Plumber,0.801,0.847,2956.04,validation
2,P00001_L003,P00001,Labour,Supervisor,0.751,0.857,1195.62,validation
3,P00001_L004,P00001,Labour,General Worker,0.759,0.875,2856.66,validation
4,P00001_L005,P00001,Labour,Supervisor,0.918,0.785,1252.25,validation
5,P00001_L006,P00001,Labour,Electrician,0.709,0.953,2372.09,validation
6,P00001_L007,P00001,Labour,Mason,0.813,0.948,1653.61,validation
7,P00001_L008,P00001,Labour,Supervisor,0.737,0.842,2411.97,validation
8,P00001_E001,P00001,Equipment,Excavator,0.928,0.905,13811.45,validation
9,P00001_E002,P00001,Equipment,Crane,0.835,0.984,9026.01,validation

In [16]:
activity_states = pd.read_csv(
    data_path / "activity_states.csv",
    low_memory=False
)

print("Shape:", activity_states.shape)
print("\nColumns:")
print(list(activity_states.columns))
print("\nData types:")
print(activity_states.dtypes)
print("\nFirst 10 rows:")
display(activity_states.head(10))

Shape: (4060623, 9)

Columns:
['project_id', 'activity_id', 'date', 'day_index', 'productivity_index', 'weather_risk', 'site_access_index', 'event_pressure', 'split']

Data types:
project_id                str
activity_id               str
date                      str
day_index               int64
productivity_index    float64
weather_risk            int64
site_access_index     float64
event_pressure        float64
split                     str
dtype: object

First 10 rows:

,project_id,activity_id,date,day_index,productivity_index,weather_risk,site_access_index,event_pressure,split
0,P00001,P00001_A0001,2024-01-01,1,0.86003,0,1.000,0.0,validation
1,P00001,P00001_A0001,2024-01-02,2,0.89787,0,1.000,0.0,validation
2,P00001,P00001_A0001,2024-01-03,3,0.86803,0,0.931,0.0,validation
3,P00001,P00001_A0001,2024-01-04,4,0.85750,0,0.989,0.0,validation
4,P00001,P00001_A0001,2024-01-05,5,0.53195,1,0.782,0.0,validation
5,P00001,P00001_A0001,2024-01-06,6,0.45969,1,0.725,0.0,validation
6,P00001,P00001_A0001,2024-01-07,7,0.77622,0,1.000,0.0,validation
7,P00001,P00001_A0001,2024-01-08,8,0.90178,0,1.000,0.0,validation
8,P00001,P00001_A0001,2024-01-09,9,0.80580,0,0.864,0.0,validation
9,P00001,P00001_A0001,2024-01-10,10,0.83736,0,1.000,0.0,validation

In [17]:
memory = pd.read_csv(
    data_path / "construction_memory.csv",
    low_memory=False
)

missing = memory.isna().sum()

print("Missing values by column:")
display(missing[missing > 0].sort_values(ascending=False))

Missing values by column:

decision_type    52115
phase            46210
activity_name    46210
resource_type    46210
event_type       27500
severity         27500
dtype: int64

In [18]:
# Search all CSV files for columns containing delay-related terms

delay_keywords = [
    "delay",
    "actual",
    "duration",
    "finish",
    "completion",
    "outcome"
]

for file in csv_files:
    df = pd.read_csv(file, low_memory=False)

    matching_columns = [
        col for col in df.columns
        if any(keyword in col.lower() for keyword in delay_keywords)
    ]

    if matching_columns:
        print("=" * 70)
        print("FILE:", file.name)
        print("Matching columns:", matching_columns)

======================================================================
FILE: activities.csv
Matching columns: ['planned_duration_days', 'project_network_duration']
======================================================================
FILE: construction_memory.csv
Matching columns: ['planned_duration_days', 'observed_delay_days']
======================================================================
FILE: counterfactuals.csv
Matching columns: ['baseline_delay_days', 'counterfactual_delay_days', 'avoided_delay_days']
======================================================================
FILE: decisions.csv
Matching columns: ['actual_decision_day', 'decision_delay_days']
======================================================================
FILE: events.csv
Matching columns: ['duration_days']
======================================================================
FILE: friction_canonical.csv
Matching columns: ['friction_duration_hours']
======================================================================
FILE: master_projects_canonical.csv
Matching columns: ['planned_duration_days', 'total_planned_duration', 'total_event_delay', 'delayed_decisions', 'total_decision_delay']
======================================================================
FILE: outcomes.csv
Matching columns: ['total_planned_duration']
======================================================================
FILE: procurement.csv
Matching columns: ['actual_lead_days', 'procurement_delay_days']
======================================================================
FILE: projects.csv
Matching columns: ['planned_duration_days']

In [19]:
# Search all CSV files for columns containing delay-related terms

delay_keywords = [
    "delay",
    "actual",
    "duration",
    "finish",
    "completion",
    "outcome"
]

for file in csv_files:
    df = pd.read_csv(file, low_memory=False)

    matching_columns = [
        col for col in df.columns
        if any(keyword in col.lower() for keyword in delay_keywords)
    ]

    if matching_columns:
        print("=" * 70)
        print("FILE:", file.name)
        print("Matching columns:", matching_columns)

======================================================================
FILE: activities.csv
Matching columns: ['planned_duration_days', 'project_network_duration']
======================================================================
FILE: construction_memory.csv
Matching columns: ['planned_duration_days', 'observed_delay_days']
======================================================================
FILE: counterfactuals.csv
Matching columns: ['baseline_delay_days', 'counterfactual_delay_days', 'avoided_delay_days']
======================================================================
FILE: decisions.csv
Matching columns: ['actual_decision_day', 'decision_delay_days']
======================================================================
FILE: events.csv
Matching columns: ['duration_days']
======================================================================
FILE: friction_canonical.csv
Matching columns: ['friction_duration_hours']
======================================================================
FILE: master_projects_canonical.csv
Matching columns: ['planned_duration_days', 'total_planned_duration', 'total_event_delay', 'delayed_decisions', 'total_decision_delay']
======================================================================
FILE: outcomes.csv
Matching columns: ['total_planned_duration']
======================================================================
FILE: procurement.csv
Matching columns: ['actual_lead_days', 'procurement_delay_days']
======================================================================
FILE: projects.csv
Matching columns: ['planned_duration_days']

In [20]:
master = pd.read_csv(
    data_path / "master_projects_canonical.csv",
    low_memory=False
)

print("Shape:", master.shape)

print("\nColumns:")
print(list(master.columns))

print("\nData types:")
print(master.dtypes)

print("\nFirst 5 rows:")
display(master.head())

Shape: (100, 29)

Columns:
['project_id', 'project_type', 'floors', 'area_m2', 'complexity', 'contractor_capability', 'resource_availability', 'management_maturity', 'weather_exposure', 'supply_chain_exposure', 'technology_maturity', 'planned_duration_days', 'planned_cost', 'total_activities', 'total_planned_duration', 'total_risk_events', 'high_critical_events', 'total_event_delay', 'total_decisions', 'delayed_decisions', 'total_decision_delay', 'total_decision_debt', 'maximum_decision_debt', 'total_friction_hours', 'friction_event_count', 'mean_friction_severity', 'max_friction_severity', 'construction_friction_index', 'split']

Data types:
project_id                         str
project_type                       str
floors                           int64
area_m2                        float64
complexity                     float64
contractor_capability          float64
resource_availability          float64
management_maturity            float64
weather_exposure               float64
supply_chain_exposure          float64
technology_maturity            float64
planned_duration_days            int64
planned_cost                   float64
total_activities                 int64
total_planned_duration           int64
total_risk_events                int64
high_critical_events             int64
total_event_delay                int64
total_decisions                  int64
delayed_decisions                int64
total_decision_delay             int64
total_decision_debt            float64
maximum_decision_debt          float64
total_friction_hours           float64
friction_event_count             int64
mean_friction_severity         float64
max_friction_severity          float64
construction_friction_index    float64
split                              str
dtype: object

First 5 rows:

,project_id,project_type,floors,area_m2,complexity,contractor_capability,resource_availability,management_maturity,weather_exposure,supply_chain_exposure,...,delayed_decisions,total_decision_delay,total_decision_debt,maximum_decision_debt,total_friction_hours,friction_event_count,mean_friction_severity,max_friction_severity,construction_friction_index,split
0,P00001,Hospital,12,31706.20,0.7112,0.9428,0.8254,0.7383,0.3867,0.4228,...,19,68,119.244503,17.215673,390.275,160,0.201215,1.0000,468.804184,validation
1,P00002,Commercial,7,56384.82,0.6882,0.8395,0.8189,0.9593,0.0714,0.3416,...,23,43,59.485701,7.127410,244.559,105,0.192810,1.0000,291.712537,train
2,P00003,Hospital,11,61848.91,0.9002,0.6385,0.9800,0.4010,0.4470,0.5078,...,32,145,326.702564,36.693229,536.975,204,0.218734,1.0000,654.429858,train
3,P00004,Industrial,5,46523.22,0.8495,0.4374,0.8357,0.7065,0.6243,0.2922,...,24,74,148.464124,23.245253,252.761,126,0.167160,0.8420,295.012408,train
4,P00005,Industrial,6,49723.66,0.7282,0.8465,0.7773,0.5635,0.3323,0.5016,...,30,128,233.890438,27.299700,261.876,114,0.191609,0.9371,312.351641,train

In [21]:
decisions = pd.read_csv(
    data_path / "decisions.csv",
    low_memory=False
)

print("Shape:", decisions.shape)

print("\nColumns:")
print(list(decisions.columns))

print("\nData types:")
print(decisions.dtypes)

print("\nFirst 5 rows:")
display(decisions.head())

Shape: (3374, 15)

Columns:
['decision_id', 'project_id', 'activity_id', 'decision_type', 'required_day', 'actual_decision_day', 'decision_delay_days', 'criticality', 'decision_status', 'dependency_exposure', 'time_exposure', 'reversibility_penalty', 'decision_debt_score', 'decision_debt_level', 'split']

Data types:
decision_id                  str
project_id                   str
activity_id                  str
decision_type                str
required_day               int64
actual_decision_day        int64
decision_delay_days        int64
criticality              float64
decision_status              str
dependency_exposure      float64
time_exposure            float64
reversibility_penalty    float64
decision_debt_score      float64
decision_debt_level          str
split                        str
dtype: object

First 5 rows:

,decision_id,project_id,activity_id,decision_type,required_day,actual_decision_day,decision_delay_days,criticality,decision_status,dependency_exposure,time_exposure,reversibility_penalty,decision_debt_score,decision_debt_level,split
0,P00001_D0001,P00001,P00001_A0023,Change Order,300,300,0,0.6967,On Time,0.69670,0.0,1.34835,0.000000,Minimal,validation
1,P00001_D0002,P00001,P00001_A0013,Quality Resolution,491,498,7,0.5519,Delayed,0.93823,0.7,1.27595,9.554268,Moderate,validation
2,P00001_D0003,P00001,P00001_A0089,Risk Response,416,416,0,0.5429,On Time,0.54290,0.0,1.27145,0.000000,Minimal,validation
3,P00001_D0004,P00001,P00001_A0019,Design Approval,471,475,4,0.6973,Delayed,0.97622,0.4,1.34865,7.433857,Moderate,validation
4,P00001_D0005,P00001,P00001_A0012,Risk Response,278,278,0,0.5728,On Time,0.57280,0.0,1.28640,0.000000,Minimal,validation

In [22]:
master = pd.read_csv(
    data_path / "master_projects_canonical.csv",
    low_memory=False
)

print("Shape:", master.shape)
print("\nColumns:")
print(list(master.columns))
print("\nData types:")
print(master.dtypes)
print("\nFirst 5 rows:")
display(master.head())

Shape: (100, 29)

Columns:
['project_id', 'project_type', 'floors', 'area_m2', 'complexity', 'contractor_capability', 'resource_availability', 'management_maturity', 'weather_exposure', 'supply_chain_exposure', 'technology_maturity', 'planned_duration_days', 'planned_cost', 'total_activities', 'total_planned_duration', 'total_risk_events', 'high_critical_events', 'total_event_delay', 'total_decisions', 'delayed_decisions', 'total_decision_delay', 'total_decision_debt', 'maximum_decision_debt', 'total_friction_hours', 'friction_event_count', 'mean_friction_severity', 'max_friction_severity', 'construction_friction_index', 'split']

Data types:
project_id                         str
project_type                       str
floors                           int64
area_m2                        float64
complexity                     float64
contractor_capability          float64
resource_availability          float64
management_maturity            float64
weather_exposure               float64
supply_chain_exposure          float64
technology_maturity            float64
planned_duration_days            int64
planned_cost                   float64
total_activities                 int64
total_planned_duration           int64
total_risk_events                int64
high_critical_events             int64
total_event_delay                int64
total_decisions                  int64
delayed_decisions                int64
total_decision_delay             int64
total_decision_debt            float64
maximum_decision_debt          float64
total_friction_hours           float64
friction_event_count             int64
mean_friction_severity         float64
max_friction_severity          float64
construction_friction_index    float64
split                              str
dtype: object

First 5 rows:

,project_id,project_type,floors,area_m2,complexity,contractor_capability,resource_availability,management_maturity,weather_exposure,supply_chain_exposure,...,delayed_decisions,total_decision_delay,total_decision_debt,maximum_decision_debt,total_friction_hours,friction_event_count,mean_friction_severity,max_friction_severity,construction_friction_index,split
0,P00001,Hospital,12,31706.20,0.7112,0.9428,0.8254,0.7383,0.3867,0.4228,...,19,68,119.244503,17.215673,390.275,160,0.201215,1.0000,468.804184,validation
1,P00002,Commercial,7,56384.82,0.6882,0.8395,0.8189,0.9593,0.0714,0.3416,...,23,43,59.485701,7.127410,244.559,105,0.192810,1.0000,291.712537,train
2,P00003,Hospital,11,61848.91,0.9002,0.6385,0.9800,0.4010,0.4470,0.5078,...,32,145,326.702564,36.693229,536.975,204,0.218734,1.0000,654.429858,train
3,P00004,Industrial,5,46523.22,0.8495,0.4374,0.8357,0.7065,0.6243,0.2922,...,24,74,148.464124,23.245253,252.761,126,0.167160,0.8420,295.012408,train
4,P00005,Industrial,6,49723.66,0.7282,0.8465,0.7773,0.5635,0.3323,0.5016,...,30,128,233.890438,27.299700,261.876,114,0.191609,0.9371,312.351641,train

In [23]:
decisions = pd.read_csv(
    data_path / "decisions.csv",
    low_memory=False
)

print("Shape:", decisions.shape)
print("\nColumns:")
print(list(decisions.columns))
print("\nData types:")
print(decisions.dtypes)
print("\nFirst 5 rows:")
display(decisions.head())

Shape: (3374, 15)

Columns:
['decision_id', 'project_id', 'activity_id', 'decision_type', 'required_day', 'actual_decision_day', 'decision_delay_days', 'criticality', 'decision_status', 'dependency_exposure', 'time_exposure', 'reversibility_penalty', 'decision_debt_score', 'decision_debt_level', 'split']

Data types:
decision_id                  str
project_id                   str
activity_id                  str
decision_type                str
required_day               int64
actual_decision_day        int64
decision_delay_days        int64
criticality              float64
decision_status              str
dependency_exposure      float64
time_exposure            float64
reversibility_penalty    float64
decision_debt_score      float64
decision_debt_level          str
split                        str
dtype: object

First 5 rows:

,decision_id,project_id,activity_id,decision_type,required_day,actual_decision_day,decision_delay_days,criticality,decision_status,dependency_exposure,time_exposure,reversibility_penalty,decision_debt_score,decision_debt_level,split
0,P00001_D0001,P00001,P00001_A0023,Change Order,300,300,0,0.6967,On Time,0.69670,0.0,1.34835,0.000000,Minimal,validation
1,P00001_D0002,P00001,P00001_A0013,Quality Resolution,491,498,7,0.5519,Delayed,0.93823,0.7,1.27595,9.554268,Moderate,validation
2,P00001_D0003,P00001,P00001_A0089,Risk Response,416,416,0,0.5429,On Time,0.54290,0.0,1.27145,0.000000,Minimal,validation
3,P00001_D0004,P00001,P00001_A0019,Design Approval,471,475,4,0.6973,Delayed,0.97622,0.4,1.34865,7.433857,Moderate,validation
4,P00001_D0005,P00001,P00001_A0012,Risk Response,278,278,0,0.5728,On Time,0.57280,0.0,1.28640,0.000000,Minimal,validation

In [24]:
decisions = pd.read_csv(
    data_path / "decisions.csv",
    low_memory=False
)

print("Shape:", decisions.shape)
print("\nColumns:")
print(list(decisions.columns))
print("\nData types:")
print(decisions.dtypes)
print("\nFirst 5 rows:")
display(decisions.head())

Shape: (3374, 15)

Columns:
['decision_id', 'project_id', 'activity_id', 'decision_type', 'required_day', 'actual_decision_day', 'decision_delay_days', 'criticality', 'decision_status', 'dependency_exposure', 'time_exposure', 'reversibility_penalty', 'decision_debt_score', 'decision_debt_level', 'split']

Data types:
decision_id                  str
project_id                   str
activity_id                  str
decision_type                str
required_day               int64
actual_decision_day        int64
decision_delay_days        int64
criticality              float64
decision_status              str
dependency_exposure      float64
time_exposure            float64
reversibility_penalty    float64
decision_debt_score      float64
decision_debt_level          str
split                        str
dtype: object

First 5 rows:

,decision_id,project_id,activity_id,decision_type,required_day,actual_decision_day,decision_delay_days,criticality,decision_status,dependency_exposure,time_exposure,reversibility_penalty,decision_debt_score,decision_debt_level,split
0,P00001_D0001,P00001,P00001_A0023,Change Order,300,300,0,0.6967,On Time,0.69670,0.0,1.34835,0.000000,Minimal,validation
1,P00001_D0002,P00001,P00001_A0013,Quality Resolution,491,498,7,0.5519,Delayed,0.93823,0.7,1.27595,9.554268,Moderate,validation
2,P00001_D0003,P00001,P00001_A0089,Risk Response,416,416,0,0.5429,On Time,0.54290,0.0,1.27145,0.000000,Minimal,validation
3,P00001_D0004,P00001,P00001_A0019,Design Approval,471,475,4,0.6973,Delayed,0.97622,0.4,1.34865,7.433857,Moderate,validation
4,P00001_D0005,P00001,P00001_A0012,Risk Response,278,278,0,0.5728,On Time,0.57280,0.0,1.28640,0.000000,Minimal,validation

In [25]:
events = pd.read_csv(
    data_path / "events.csv",
    low_memory=False
)

print("Shape:", events.shape)
print("\nColumns:")
print(list(events.columns))
print("\nData types:")
print(events.dtypes)
print("\nFirst 5 rows:")
display(events.head())

Shape: (27989, 10)

Columns:
['event_id', 'project_id', 'date', 'activity_id', 'event_type', 'severity', 'duration_days', 'cause_node', 'impact_factor', 'split']

Data types:
event_id             str
project_id           str
date                 str
activity_id          str
event_type           str
severity             str
duration_days      int64
cause_node           str
impact_factor    float64
split                str
dtype: object

First 5 rows:

,event_id,project_id,date,activity_id,event_type,severity,duration_days,cause_node,impact_factor,split
0,P00001_E00001,P00001,2024-01-02,P00001_A0026,Rework,Medium,1,Rework,0.50,validation
1,P00001_E00002,P00001,2024-01-13,P00001_A0091,Heavy Rainfall,Low,1,Weather,0.25,validation
2,P00001_E00003,P00001,2024-01-13,P00001_A0092,Subcontractor Delay,Medium,26,Subcontractor Delay,0.50,validation
3,P00001_E00004,P00001,2024-01-16,P00001_A0043,Equipment Breakdown,Low,2,Equipment Breakdown,0.25,validation
4,P00001_E00005,P00001,2024-01-16,P00001_A0019,Material Shortage,Medium,6,Material Shortage,0.50,validation

In [26]:
rework = pd.read_csv(
    data_path / "rework.csv",
    low_memory=False
)

print("Shape:", rework.shape)
print("\nColumns:")
print(list(rework.columns))
print("\nData types:")
print(rework.dtypes)
print("\nFirst 5 rows:")
display(rework.head())

Shape: (1858, 7)

Columns:
['rework_id', 'project_id', 'event_id', 'activity_id', 'rework_days', 'rework_cost', 'split']

Data types:
rework_id          str
project_id         str
event_id           str
activity_id        str
rework_days      int64
rework_cost    float64
split              str
dtype: object

First 5 rows:

,rework_id,project_id,event_id,activity_id,rework_days,rework_cost,split
0,RW0000001,P00001,P00001_E00006,P00001_A0025,1,9578.96,validation
1,RW0000002,P00001,P00001_E00014,P00001_A0033,6,55095.02,validation
2,RW0000003,P00001,P00001_E00028,P00001_A0089,1,10498.68,validation
3,RW0000004,P00001,P00001_E00034,P00001_A0014,4,12702.75,validation
4,RW0000005,P00001,P00001_E00035,P00001_A0071,6,50161.97,validation

In [27]:
procurement = pd.read_csv(
    data_path / "procurement.csv",
    low_memory=False
)

print("Shape:", procurement.shape)
print("\nColumns:")
print(list(procurement.columns))
print("\nData types:")
print(procurement.dtypes)
print("\nFirst 5 rows:")
display(procurement.head())

Shape: (800, 8)

Columns:
['procurement_id', 'project_id', 'material', 'planned_lead_days', 'actual_lead_days', 'procurement_delay_days', 'supply_chain_risk', 'split']

Data types:
procurement_id                str
project_id                    str
material                      str
planned_lead_days           int64
actual_lead_days            int64
procurement_delay_days      int64
supply_chain_risk         float64
split                         str
dtype: object

First 5 rows:

,procurement_id,project_id,material,planned_lead_days,actual_lead_days,procurement_delay_days,supply_chain_risk,split
0,P00001_PO001,P00001,Steel,17,17,0,0.4228,validation
1,P00001_PO002,P00001,Cement,17,32,15,0.4228,validation
2,P00001_PO003,P00001,Concrete,4,18,14,0.4228,validation
3,P00001_PO004,P00001,Brick,9,21,12,0.4228,validation
4,P00001_PO005,P00001,Tiles,29,29,0,0.4228,validation

In [28]:
resources = pd.read_csv(
    data_path / "resources.csv",
    low_memory=False
)

print("Shape:", resources.shape)
print("\nColumns:")
print(list(resources.columns))
print("\nData types:")
print(resources.dtypes)
print("\nFirst 5 rows:")
display(resources.head())

Shape: (2748, 8)

Columns:
['resource_id', 'project_id', 'resource_category', 'resource_type', 'capacity', 'availability', 'daily_cost', 'split']

Data types:
resource_id              str
project_id               str
resource_category        str
resource_type            str
capacity             float64
availability         float64
daily_cost           float64
split                    str
dtype: object

First 5 rows:

,resource_id,project_id,resource_category,resource_type,capacity,availability,daily_cost,split
0,P00001_L001,P00001,Labour,Plumber,0.735,0.996,1375.29,validation
1,P00001_L002,P00001,Labour,Plumber,0.801,0.847,2956.04,validation
2,P00001_L003,P00001,Labour,Supervisor,0.751,0.857,1195.62,validation
3,P00001_L004,P00001,Labour,General Worker,0.759,0.875,2856.66,validation
4,P00001_L005,P00001,Labour,Supervisor,0.918,0.785,1252.25,validation

In [29]:
activity_states = pd.read_csv(
    data_path / "activity_states.csv",
    low_memory=False
)

print("Shape:", activity_states.shape)
print("\nColumns:")
print(list(activity_states.columns))
print("\nData types:")
print(activity_states.dtypes)
print("\nFirst 5 rows:")
display(activity_states.head())

Shape: (4060623, 9)

Columns:
['project_id', 'activity_id', 'date', 'day_index', 'productivity_index', 'weather_risk', 'site_access_index', 'event_pressure', 'split']

Data types:
project_id                str
activity_id               str
date                      str
day_index               int64
productivity_index    float64
weather_risk            int64
site_access_index     float64
event_pressure        float64
split                     str
dtype: object

First 5 rows:

,project_id,activity_id,date,day_index,productivity_index,weather_risk,site_access_index,event_pressure,split
0,P00001,P00001_A0001,2024-01-01,1,0.86003,0,1.000,0.0,validation
1,P00001,P00001_A0001,2024-01-02,2,0.89787,0,1.000,0.0,validation
2,P00001,P00001_A0001,2024-01-03,3,0.86803,0,0.931,0.0,validation
3,P00001,P00001_A0001,2024-01-04,4,0.85750,0,0.989,0.0,validation
4,P00001,P00001_A0001,2024-01-05,5,0.53195,1,0.782,0.0,validation

In [30]:
# Show only delay-related columns from the master project table

delay_columns = [
    col for col in master.columns
    if "delay" in col.lower()
]

print("Delay-related columns:")
print(delay_columns)

print("\nSample values:")
display(master[["project_id"] + delay_columns].head(10))

Delay-related columns:
['total_event_delay', 'delayed_decisions', 'total_decision_delay']

Sample values:

  project_id  total_event_delay  delayed_decisions  total_decision_delay
0     P00001               1938                 19                    68
1     P00002               1409                 23                    43
2     P00003               2251                 32                   145
3     P00004               1689                 24                    74
4     P00005               1715                 30                   128
5     P00006               1723                 26                    96
6     P00007               1826                 30                   109
7     P00008               1463                 25                    81
8     P00009               2072                 20                    37
9     P00010               1311                 17                    65

In [31]:
for col in delay_columns:
    print("=" * 60)
    print(col)
    print("Minimum:", master[col].min())
    print("Maximum:", master[col].max())
    print("Mean:", master[col].mean())
    print("Unique values:", master[col].nunique())

============================================================
total_event_delay
Minimum: 796
Maximum: 2629
Mean: 1556.47
Unique values: 97
============================================================
delayed_decisions
Minimum: 12
Maximum: 34
Mean: 23.47
Unique values: 23
============================================================
total_decision_delay
Minimum: 20
Maximum: 190
Mean: 84.41
Unique values: 69

In [32]:
print(master["split"].value_counts())

split
train         70
validation    15
test          15
Name: count, dtype: int64

In [33]:
dictionary = pd.read_csv(
    data_path / "DATA_DICTIONARY.csv",
    low_memory=False
)

delay_info = dictionary[
    dictionary["variable"].str.contains(
        "delay|decision|event",
        case=False,
        na=False
    )
]

display(delay_info)

,dataset,variable,datatype,description
70,activity_states,event_pressure,float64,Synthetic event-pressure indicator associated ...
77,procurement,procurement_delay_days,int64,Difference between actual and planned procurem...
80,decisions,decision_id,object,Variable from the decisions dataset.
83,decisions,decision_type,object,Variable from the decisions dataset.
85,decisions,actual_decision_day,int64,Variable from the decisions dataset.
86,decisions,decision_delay_days,int64,Variable from the decisions dataset.
88,decisions,decision_status,object,Variable from the decisions dataset.
92,decisions,decision_debt_score,float64,Variable from the decisions dataset.
93,decisions,decision_debt_level,object,Variable from the decisions dataset.
95,events,event_id,object,Unique synthetic construction-event identifier.
99,events,event_type,object,Variable from the events dataset.
107,rework,event_id,object,Unique synthetic construction-event identifier.
119,intervention_options,event_id,object,Unique synthetic construction-event identifier.
122,intervention_options,event_type,object,Variable from the intervention_options dataset.
130,counterfactuals,event_id,object,Unique synthetic construction-event identifier.
133,counterfactuals,baseline_delay_days,float64,Synthetic project or activity delay under the ...
134,counterfactuals,counterfactual_delay_days,float64,Synthetic delay under the corresponding counte...
135,counterfactuals,avoided_delay_days,float64,Synthetic delay reduction associated with the ...
146,construction_memory,event_type,float64,Variable from the construction_memory dataset.
147,construction_memory,decision_type,float64,Variable from the construction_memory dataset.
151,construction_memory,observed_delay_days,float64,Variable from the construction_memory dataset.
157,construction_memory,decision_debt_score,float64,Variable from the construction_memory dataset.
170,friction_summary_canonical,friction_events,int64,Variable from the friction_summary_canonical d...
186,master_projects_canonical,total_risk_events,int64,Variable from the master_projects_canonical da...
187,master_projects_canonical,high_critical_events,int64,Variable from the master_projects_canonical da...
188,master_projects_canonical,total_event_delay,int64,Variable from the master_projects_canonical da...
189,master_projects_canonical,total_decisions,int64,Variable from the master_projects_canonical da...
190,master_projects_canonical,delayed_decisions,int64,Variable from the master_projects_canonical da...
191,master_projects_canonical,total_decision_delay,int64,Variable from the master_projects_canonical da...
192,master_projects_canonical,total_decision_debt,float64,Variable from the master_projects_canonical da...
193,master_projects_canonical,maximum_decision_debt,float64,Variable from the master_projects_canonical da...
195,master_projects_canonical,friction_event_count,int64,Variable from the master_projects_canonical da...

In [34]:
dictionary = pd.read_csv(
    data_path / "DATA_DICTIONARY.csv",
    low_memory=False
)

delay_info = dictionary[
    dictionary["variable"].str.contains(
        "delay|decision|event",
        case=False,
        na=False
    )
]

display(delay_info)

,dataset,variable,datatype,description
70,activity_states,event_pressure,float64,Synthetic event-pressure indicator associated ...
77,procurement,procurement_delay_days,int64,Difference between actual and planned procurem...
80,decisions,decision_id,object,Variable from the decisions dataset.
83,decisions,decision_type,object,Variable from the decisions dataset.
85,decisions,actual_decision_day,int64,Variable from the decisions dataset.
86,decisions,decision_delay_days,int64,Variable from the decisions dataset.
88,decisions,decision_status,object,Variable from the decisions dataset.
92,decisions,decision_debt_score,float64,Variable from the decisions dataset.
93,decisions,decision_debt_level,object,Variable from the decisions dataset.
95,events,event_id,object,Unique synthetic construction-event identifier.
99,events,event_type,object,Variable from the events dataset.
107,rework,event_id,object,Unique synthetic construction-event identifier.
119,intervention_options,event_id,object,Unique synthetic construction-event identifier.
122,intervention_options,event_type,object,Variable from the intervention_options dataset.
130,counterfactuals,event_id,object,Unique synthetic construction-event identifier.
133,counterfactuals,baseline_delay_days,float64,Synthetic project or activity delay under the ...
134,counterfactuals,counterfactual_delay_days,float64,Synthetic delay under the corresponding counte...
135,counterfactuals,avoided_delay_days,float64,Synthetic delay reduction associated with the ...
146,construction_memory,event_type,float64,Variable from the construction_memory dataset.
147,construction_memory,decision_type,float64,Variable from the construction_memory dataset.
151,construction_memory,observed_delay_days,float64,Variable from the construction_memory dataset.
157,construction_memory,decision_debt_score,float64,Variable from the construction_memory dataset.
170,friction_summary_canonical,friction_events,int64,Variable from the friction_summary_canonical d...
186,master_projects_canonical,total_risk_events,int64,Variable from the master_projects_canonical da...
187,master_projects_canonical,high_critical_events,int64,Variable from the master_projects_canonical da...
188,master_projects_canonical,total_event_delay,int64,Variable from the master_projects_canonical da...
189,master_projects_canonical,total_decisions,int64,Variable from the master_projects_canonical da...
190,master_projects_canonical,delayed_decisions,int64,Variable from the master_projects_canonical da...
191,master_projects_canonical,total_decision_delay,int64,Variable from the master_projects_canonical da...
192,master_projects_canonical,total_decision_debt,float64,Variable from the master_projects_canonical da...
193,master_projects_canonical,maximum_decision_debt,float64,Variable from the master_projects_canonical da...
195,master_projects_canonical,friction_event_count,int64,Variable from the master_projects_canonical da...

In [1]:
import matplotlib.pyplot as plt

print("Matplotlib imported successfully")

Matplotlib imported successfully